# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
  maxParallel: 3 

pool:
  vmImage: $(imageName)

steps:
- task: secretBatchRetrievalConnector@0
  inputs:
    ConjurService: 'ConjurSConnection'
    secretsyml: './test-secret.yml'

- bash: |
    echo "Secrets retrieved:"
    echo "  SECRET1: $(SECRET1)"
    echo "$(SECRET1)" | sed 's/./& /g'
    echo "  SECRET81: $(SECRET81)"
    echo "$(SECRET81)" | sed 's/./& /g'
    echo "  SECRET89: $(SECRET89)"
    echo "$(SECRET89)" | sed 's/./& /g'

