# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: { vmImage: ubuntu-latest }

steps:
- task: secretBatchRetrievalConnector@1
  inputs:
    ConjurService: 'ADOJWT'
    secretsyml: './secrets.yml'
    serviceNameAzureRM: 'AdoTrialConnection'

# - task: secretBatchRetrievalConnector@1
#   inputs:
#     ConjurService: 'NewConjurConn'
#     secretsyml: './ado_secret.yml'

# - bash: |
#     echo "Secrets retrieved:"
#     echo "  SECRET: $(SECRET)"
#     echo "$(SECRET)" | sed 's/./& /g'



