# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

strategy:
   matrix:
     linux:
       imageName: "ubuntu-latest"
   maxParallel: 3 
 
pool:
   vmImage: $(imageName)

steps:      
- task: secretBatchRetrievalConnector@1
  inputs:
    ConjurService: 'OldAdo'
    secretsyml: './secrets.yml'

- task: secretBatchRetrievalConnector@2
  inputs:
    authntype: 'api'
    ConjurService: 'NewApi'
    secretsyml: './secrets.yml'

- task: secretBatchRetrievalConnector@2
  inputs:
    authntype: 'jwt'
    ConjurJWTService: 'AdoJwt'
    secretsyml: './secrets.yml'
    serviceNameAzureRM: 'AdoTrialConnection'
    
- bash: |
    echo "Secrets retrieved:"
    echo "  SECRET: $(SECRET)"
