# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

# strategy:
#     matrix:
#       linux:
#         imageName: "ubuntu-latest"
#     maxParallel: 3 
 
# pool:
#     vmImage: $(imageName)
pool: default

variables:
  NODE_EXTRA_CA_CERTS: /Users/nirupma.verma/Downloads/conjur_cert.pem

steps:    
# - task: secretBatchRetrievalConnector@1
#   inputs:
#     ConjurService: 'Old1.2.4Exten'
#     secretsyml: './secrets.yml'
- task: secretBatchRetrievalConnector@1
  inputs:
    authntype: 'api'
    ConjurService: 'TeleCh'
    secretsyml: './edge.yml'

# - task: secretBatchRetrievalConnector@1
#   inputs:
#     authntype: 'jwt'
#     ConjurJWTService: 'AdoJwt'
#     secretsyml: './secrets.yml'
#     serviceNameAzureRM: 'AdoTrialConnection'

# - task: secretBatchRetrievalConnector@1
#   inputs:
#     authntype: 'api'
#     ConjurService: 'Old1.2.4Exten'
#     secretsyml: './secrets.yml'
    
- bash: |
    echo "Secrets retrieved:"
    echo "  SECRET: $(SECRET)"
